### ISSUE TITLE
Doesn't work with youtube's new theme

### ISSUE THREAD

**Issue by chalkos** [SimenMH/better-youtube-theatre-mode#1]
Hello and thanks for the extension, it has been working for a long time without issues!

Today I noticed that youtube changed its theme to swap the placement of suggested videos and the description/comments, so that suggested videos are now on the left and title/description/comments are on the right. It seems they are phasing out this theme change for some accounts, and the full-height theatre mode is not working with it.
Could you take a look?

Thanks!

**Comment by SimenMH** [comment]
Hi Chalkos, I'm glad you've been getting use of the extension!

Unfortunately I don't have access to the new UI yet on any of my accounts, and I can't find a way to get access to it either. It might take a while until I will be able to make the extension compatible with the new UI. But as soon as I get access to it, I will push a new update out.
